apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-test-initializer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ruhsi/quarkus-test-ci.git
    targetRevision: master
    path: appsets/
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-test
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true