apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: quarkus-test-dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Ruhsi/quarkus-test-ci.git
      revision: master
      directories:
      - path: apps/*/envs/dev

  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}' 
    spec:
      project: default
      source:
        repoURL: https://github.com/Ruhsi/quarkus-test-ci.git
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
      